// Power Query (M) for the Olist Operations Intelligence import package. GENERATED by scripts/export_powerbi.py; do not edit by hand.
// 1) Home > Manage Parameters > New Parameter: name DataFolder, type Text, value = full path of powerbi\data\ INCLUDING a trailing backslash.
// 2) For each block below: Home > New Source > Blank Query > Advanced Editor, paste the block, name the query exactly as in the header comment.
// All queries parse numbers and dates with the en-US culture, so the result does not depend on the Windows regional settings.

// ---------------- query name: fact_orders ----------------
let
    Source   = Csv.Document(File.Contents(DataFolder & "fact_orders.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed    = Table.TransformColumnTypes(Promoted, {{"order_id", type text}, {"purchase_date", type date}, {"customer_state", type text}, {"order_status", type text}, {"fulfilment_class", type text}, {"fulfilment_label", type text}, {"in_window", Int64.Type}, {"is_delivery_kpi_eligible", Int64.Type}, {"is_late", Int64.Type}, {"is_severe_late", Int64.Type}, {"delivery_outcome", type text}, {"lead_time_days", type number}, {"promised_lead_days", Int64.Type}, {"promise_error_days", Int64.Type}, {"days_late_band", type text}, {"promised_group", type text}, {"review_row_count", Int64.Type}, {"review_score", Int64.Type}, {"review_before_delivery_flag", Int64.Type}, {"is_review_p0", Int64.Type}, {"is_review_p1", Int64.Type}, {"is_single_seller", Int64.Type}, {"ts_sequence_violation", Int64.Type}}, "en-US")
in
    Typed

// ---------------- query name: fact_seller_orders ----------------
let
    Source   = Csv.Document(File.Contents(DataFolder & "fact_seller_orders.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed    = Table.TransformColumnTypes(Promoted, {{"order_id", type text}, {"seller_id", type text}, {"seller_state", type text}, {"customer_state", type text}, {"lane", type text}, {"purchase_date", type date}, {"is_cross_state", Int64.Type}, {"distance_km", type number}, {"distance_band", type text}, {"promised_group", type text}, {"is_late", Int64.Type}, {"is_severe_late", Int64.Type}, {"delivery_outcome", type text}, {"lead_time_days", type number}, {"promised_lead_days", Int64.Type}, {"promise_error_days", Int64.Type}, {"days_late_band", type text}, {"review_row_count", Int64.Type}, {"review_score", Int64.Type}, {"review_before_delivery_flag", Int64.Type}, {"is_review_p0", Int64.Type}, {"is_review_p1", Int64.Type}}, "en-US")
in
    Typed

// ---------------- query name: dim_date ----------------
let
    Source   = Csv.Document(File.Contents(DataFolder & "dim_date.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed    = Table.TransformColumnTypes(Promoted, {{"date_key", type date}, {"year", Int64.Type}, {"month_number", Int64.Type}, {"year_month", type text}, {"month_start", type date}, {"month_label", type text}, {"month_sort", Int64.Type}, {"is_in_window", Int64.Type}}, "en-US")
in
    Typed

// ---------------- query name: dim_state ----------------
let
    Source   = Csv.Document(File.Contents(DataFolder & "dim_state.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed    = Table.TransformColumnTypes(Promoted, {{"state_code", type text}, {"state_name", type text}, {"macro_region", type text}, {"macro_region_order", Int64.Type}}, "en-US")
in
    Typed

// ---------------- query name: dim_origin_state ----------------
let
    Source   = Csv.Document(File.Contents(DataFolder & "dim_origin_state.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed    = Table.TransformColumnTypes(Promoted, {{"origin_state_code", type text}, {"origin_state_name", type text}, {"origin_macro_region", type text}, {"origin_macro_region_order", Int64.Type}}, "en-US")
in
    Typed

// ---------------- query name: dim_seller ----------------
let
    Source   = Csv.Document(File.Contents(DataFolder & "dim_seller.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed    = Table.TransformColumnTypes(Promoted, {{"seller_id", type text}, {"seller_label", type text}}, "en-US")
in
    Typed

// ---------------- query name: snap_priority_candidates ----------------
let
    Source   = Csv.Document(File.Contents(DataFolder & "snap_priority_candidates.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed    = Table.TransformColumnTypes(Promoted, {{"snapshot_level", type text}, {"segment", type text}, {"segment_label", type text}, {"origin_state", type text}, {"destination_state", type text}, {"display_region", type text}, {"northeast_bound", Int64.Type}, {"tier", type text}, {"tier_sort", Int64.Type}, {"tier_x10", type text}, {"tier_x30", type text}, {"tier_excl_episodes", type text}, {"consistency", type text}, {"eligible", Int64.Type}, {"low_confidence", Int64.Type}, {"signal", Int64.Type}, {"n_delivered", Int64.Type}, {"n_late", Int64.Type}, {"late_rate", type number}, {"late_rate_lo", type number}, {"late_rate_hi", type number}, {"reference_late_rate", type number}, {"expected_late", type number}, {"excess_late", type number}, {"excess_late_lo", type number}, {"excess_late_hi", type number}, {"oe_s1", type number}, {"n_h1", Int64.Type}, {"rate_h1", type number}, {"n_h2", Int64.Type}, {"rate_h2", type number}, {"episode_late_share", type number}, {"rank_excess_late", Int64.Type}, {"n_reviewed_p0", Int64.Type}, {"p0_share_of_delivered", type number}, {"n_low", Int64.Type}, {"low_rate", type number}, {"excess_low", type number}, {"excess_low_after", type number}, {"early_review_share", type number}, {"low_ontime_rate", type number}, {"low_ontime_rate_lo", type number}, {"low_ontime_rate_hi", type number}, {"excess_low_ontime", type number}}, "en-US")
in
    Typed

// ---------------- query name: snap_tier_counts ----------------
let
    Source   = Csv.Document(File.Contents(DataFolder & "snap_tier_counts.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed    = Table.TransformColumnTypes(Promoted, {{"snapshot_level", type text}, {"min_excess_late", Int64.Type}, {"is_primary", Int64.Type}, {"investigate", Int64.Type}, {"watch", Int64.Type}, {"no_signal", Int64.Type}, {"insufficient_data", Int64.Type}}, "en-US")
in
    Typed

// ---------------- query name: snap_overlap ----------------
let
    Source   = Csv.Document(File.Contents(DataFolder & "snap_overlap.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed    = Table.TransformColumnTypes(Promoted, {{"row_type", type text}, {"label", type text}, {"in_state", Int64.Type}, {"in_lane", Int64.Type}, {"in_seller", Int64.Type}, {"n_orders", Int64.Type}, {"n_late", Int64.Type}, {"excess_vs_ref", type number}}, "en-US")
in
    Typed

// ---------------- query name: snap_metadata ----------------
let
    Source   = Csv.Document(File.Contents(DataFolder & "snap_metadata.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
    Typed    = Table.TransformColumnTypes(Promoted, {{"key", type text}, {"value", type text}, {"description", type text}}, "en-US")
in
    Typed
