"""Generate reports/data_model_validation.md from the built DuckDB model.

Usage (after `python scripts/build_model.py`):
    python scripts/build_validation_report.py

Every number in the tables is queried from the model, recomputed with the independent pandas reference,
or taken from the pytest run executed by this script. Narrative sections (deviations, issues) are static
text written after inspecting those results.
"""
from __future__ import annotations

import hashlib
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tests"))
sys.path.insert(0, str(ROOT / "scripts"))

import build_model  # noqa: E402
import reference_pandas  # noqa: E402
from anchors import ANCHORS  # noqa: E402

DB = build_model.DEFAULT_DB
RAW = build_model.DEFAULT_RAW
OUT = ROOT / "reports" / "data_model_validation.md"
JUNIT = ROOT / "data" / "processed" / "pytest_junit.xml"


def md_table(headers: list[str], rows: list[list]) -> str:
    def fmt(v):
        if isinstance(v, float):
            return f"{v:,.4f}"
        if isinstance(v, int):
            return f"{v:,}"
        return str(v)
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines += ["| " + " | ".join(fmt(c) for c in r) + " |" for r in rows]
    return "\n".join(lines)


def run_pytest() -> tuple[int, list[tuple[str, str, float]], str]:
    JUNIT.parent.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run([sys.executable, "-m", "pytest", "-q", f"--junitxml={JUNIT}"], cwd=ROOT,
                          capture_output=True, text=True)
    cases = []
    for tc in ET.parse(JUNIT).getroot().iter("testcase"):
        status = "FAIL" if (tc.find("failure") is not None or tc.find("error") is not None) else (
            "SKIP" if tc.find("skipped") is not None else "PASS")
        cases.append((tc.get("name"), status, float(tc.get("time", 0))))
    summary = proc.stdout.strip().splitlines()[-1] if proc.stdout.strip() else "(no output)"
    return proc.returncode, cases, summary


def main() -> int:
    if not DB.exists():
        print("Model not found. Run: python scripts/build_model.py", file=sys.stderr)
        return 1
    con = duckdb.connect(str(DB), read_only=True)
    q = lambda sql: con.execute(sql).fetchall()      # noqa: E731
    q1 = lambda sql: con.execute(sql).fetchone()[0]  # noqa: E731

    rc, cases, pytest_summary = run_pytest()
    ref = reference_pandas.compute_reference(RAW)
    build_results = build_model.build(RAW, ROOT / "data" / "processed" / "_report_rebuild.duckdb", verbose=False)
    (ROOT / "data" / "processed" / "_report_rebuild.duckdb").unlink(missing_ok=True)

    P = dict(zip(["window_start", "window_end_exclusive", "severe_late_days", "reference_date"],
                 q("SELECT window_start, window_end_exclusive, severe_late_days, reference_date FROM model_params")[0]))
    out: list[str] = []
    w = out.append

    w("# Data Model Validation Report (Phase 1)\n")
    w("Generated by `scripts/build_validation_report.py` from the DuckDB model built by `scripts/build_model.py` "
      "(SQL in `sql/`). Raw CSVs in `data/raw/` are read-only and were hash-checked unchanged by the test suite. "
      "Analytical data model only: no EDA, hypothesis tests, seller rankings, dashboard or ML were performed.\n")
    w(f"Model parameters: window = purchases {P['window_start']} to before {P['window_end_exclusive']} "
      f"(2017-01 to 2018-08); severe lateness = promise error > {P['severe_late_days']} calendar days; "
      f"reference date = {P['reference_date']} (latest observed event timestamp in the extract).\n")

    overall = "PASS" if rc == 0 else "FAIL"
    w(f"**Overall result: {overall}.** {pytest_summary}; {len(build_results)} structural build assertions, "
      f"{sum(1 for v in build_results.values() if v == 0)} passed.\n")

    # ---------------------------------------------------------------- 1 schema
    w("## 1. Final schema\n")
    grains = {
        "fact_orders": ("order", "`order_id`", "All orders kept; eligibility via flags; items/reviews pre-aggregated"),
        "fact_order_items": ("order item", "`order_id`, `order_item_id`", "Item-level distance, category, cross-state"),
        "fact_reviews": ("order x review", "`order_id`, `review_id`", "No 'latest review' flag by design"),
        "bridge_order_seller": ("order x seller", "`order_id`, `seller_id`", "Validation only (not for Power BI)"),
        "v_single_seller_orders": ("order (eligible single-seller)", "`order_id`", "VIEW; window + delivered-with-date + one seller"),
        "dim_seller": ("seller", "`seller_id`", "With seller macro-region"),
        "dim_product": ("product", "`product_id`", "English category with Portuguese fallback"),
        "dim_zip_geo": ("ZIP prefix", "`zip_code_prefix`", "Median centroid of distinct in-box points"),
        "dim_state": ("state", "`state_code`", "27 UFs + IBGE macro-region (external reference)"),
        "dim_date": ("calendar date", "`date_key`", "2016-01-01 to 2018-12-31"),
        "model_params": ("single row", "n/a", "Window, thresholds, reference date, geo box"),
    }
    rows = []
    for t, (grain, key, note) in grains.items():
        n = q1(f"SELECT count(*) FROM {t}")
        ncol = q1(f"SELECT count(*) FROM information_schema.columns WHERE table_name = '{t}'")
        rows.append([f"`{t}`", grain, key, n, ncol, note])
    w(md_table(["Table / view", "Grain (one row per)", "Primary key", "Rows", "Cols", "Notes"], rows))
    w("\nStaging tables (typed copies of the raw CSVs): " + ", ".join(
        f"`{t}` ({q1(f'SELECT count(*) FROM {t}'):,})" for (t,) in q(
            "SELECT table_name FROM information_schema.tables WHERE table_name LIKE 'stg_%' ORDER BY 1")) + ".\n")
    w("Columns of `fact_orders`: " + ", ".join(f"`{c}`" for (c,) in q(
        "SELECT column_name FROM information_schema.columns WHERE table_name = 'fact_orders' ORDER BY ordinal_position")) + ".\n")
    w("Join keys: `fact_orders.customer_state` -> `dim_state.state_code`; `fact_orders.purchase_date`/`estimated_date` -> "
      "`dim_date.date_key`; `fact_order_items.order_id` -> `fact_orders.order_id`; `fact_order_items.seller_id` -> "
      "`dim_seller.seller_id`; `fact_order_items.product_id` -> `dim_product.product_id`; `v_single_seller_orders.seller_id` "
      "-> `dim_seller.seller_id`; ZIP prefixes -> `dim_zip_geo.zip_code_prefix` (used for distance only).\n")

    # ---------------------------------------------------------------- 2 waterfall
    w("## 2. Population waterfall\n")
    total = q1("SELECT count(*) FROM fact_orders")
    inw = q1("SELECT count(*) FROM fact_orders WHERE in_window")
    fc = dict(q("SELECT fulfilment_class, count(*) FROM fact_orders WHERE in_window GROUP BY 1"))
    dw = q1("SELECT count(*) FROM fact_orders WHERE is_delivery_kpi_eligible")
    ss = q1("SELECT count(*) FROM v_single_seller_orders")
    p0, zero, multi = q("SELECT count(*) FILTER (WHERE review_row_count = 1), count(*) FILTER (WHERE review_row_count = 0), "
                        "count(*) FILTER (WHERE review_row_count > 1) FROM fact_orders WHERE is_delivery_kpi_eligible")[0]
    p1 = q1("SELECT count(*) FROM fact_orders WHERE is_review_p1_eligible")
    wf = [
        ["All orders", total, "", "99,441 (profile_stats.json)"],
        ["In purchase window 2017-01..2018-08", inw, f"{total - inw:,} purchased outside window", "n/a (new)"],
        ["Delivered with delivery date (delivery-KPI population)", dw,
         f"{inw - dw:,} in window not delivered-with-date (see classes below)", "96,203"],
        ["Single-seller subset (seller-KPI population)", ss, f"{dw - ss:,} multi-seller orders excluded", "94,931"],
        ["Review population P0 (exactly one review row)", p0, f"{zero:,} with no review; {multi:,} with several rows", "n/a (new)"],
        ["Review sensitivity P1 (P0 minus reviews dated before delivery)", p1, f"{p0 - p1:,} early reviews removed", "n/a (new)"],
    ]
    w(md_table(["Step", "Orders", "Excluded at this step", "Established anchor"], wf))
    w("\n### Fulfilment classes (blueprint R9), in window and all months\n")
    order = ["delivered_on_time", "delivered_late", "cancelled_unavailable", "open_past_promise", "open_not_yet_due",
             "delivered_status_no_date"]
    fa = dict(q("SELECT fulfilment_class, count(*) FROM fact_orders GROUP BY 1"))
    w(md_table(["Class", "In window", "% of window orders", "All months"],
               [[c, fc.get(c, 0), f"{100 * fc.get(c, 0) / inw:.2f}%", fa.get(c, 0)] for c in order] +
               [["**Total**", inw, "100%", total]]))
    w("\nOriginal order statuses are preserved in `fact_orders.order_status`. Open classes by status (window):\n")
    w(md_table(["order_status", "fulfilment_class", "Orders"], [list(r) for r in q(
        "SELECT order_status, fulfilment_class, count(*) FROM fact_orders WHERE in_window AND fulfilment_class LIKE 'open%' "
        "GROUP BY 1, 2 ORDER BY 1, 2")]))
    w("\nCancelled/unavailable by status (window): " + ", ".join(f"{s}: {n:,}" for s, n in q(
        "SELECT order_status, count(*) FROM fact_orders WHERE in_window AND fulfilment_class = 'cancelled_unavailable' GROUP BY 1 ORDER BY 1")) +
      ". None is classified as open past promise (asserted).\n")
    w("\n### Window-restricted counts that were previously uncomputed (blueprint [TBC])\n")
    w(md_table(["Quantity", "Count", "Pandas reference"], [
        ["Delivered-in-window orders with exactly one review (P0)", p0, ref["review_p0_window"]],
        ["Delivered-in-window orders with no review", zero, ref["review_zero_window"]],
        ["Delivered-in-window orders with several review rows", multi, ref["review_multi_window"]],
        ["P0 reviews created before the delivery date", p0 - p1, ref["early_review_window"]],
        ["P1 (P0 excluding early reviews)", p1, ref["review_p1_window"]],
        ["P0 orders delivered late", q1("SELECT count(*) FROM fact_orders WHERE is_review_kpi_eligible AND is_late_calendar"), ref["late_n_p0_window"]],
    ]))

    # ---------------------------------------------------------------- 3 KPI reconciliation
    w("\n## 3. KPI reconciliation\n")
    w("Integer counts must match exactly. Rates are compared with numeric tolerances (never rounded-string equality). "
      "Anchors come from `profile_stats.json`, `kpi_validation_stats.json` and `dataset_feasibility.md`; expected values "
      "were not adjusted to fit the model.\n")
    late_n, late_d = q("SELECT sum(is_late_calendar::INT), count(*) FROM fact_orders WHERE is_delivery_kpi_eligible")[0]
    rec = [
        ["Orders", ANCHORS["orders"], q1("SELECT count(*) FROM fact_orders"), ref["n_orders"]],
        ["Order items", ANCHORS["items"], q1("SELECT count(*) FROM fact_order_items"), ref["n_items"]],
        ["Multi-seller orders", ANCHORS["multi_seller_orders"], q1("SELECT count(*) FROM fact_orders WHERE n_sellers > 1"), ref["multi_seller_orders"]],
        ["Delivered with date, all months", ANCHORS["delivered_dated_all"], q1("SELECT count(*) FROM fact_orders WHERE is_delivered_dated"), ref["delivered_dated_all"]],
        ["Delivered with date, window", ANCHORS["delivered_dated_window"], dw, ref["delivered_dated_window"]],
        ["Single-seller delivered, window", ANCHORS["single_seller_window"], ss, ref["single_seller_window"]],
        ["Sellers in single-seller window population", ANCHORS["sellers_window"], q1("SELECT count(DISTINCT seller_id) FROM v_single_seller_orders"), ref["n_sellers_window"]],
        ["Late (calendar), all months", ANCHORS["late_all"], q1("SELECT count(*) FROM fact_orders WHERE is_late_calendar"), ref["late_all"]],
        ["Late (exact timestamp), all months", ANCHORS["late_exact_all"], q1("SELECT count(*) FROM fact_orders WHERE is_late_exact"), ref["late_exact_all"]],
        ["Late (calendar), window", "n/a (new)", late_n, ref["late_window"]],
        ["Timestamp-sequence violations", ANCHORS["ts_violations"], q1("SELECT count(*) FROM fact_orders WHERE ts_sequence_violation"), ref["ts_violations"]],
        ["Status/date conflicts", ANCHORS["status_date_conflicts"], q1("SELECT count(*) FROM fact_orders WHERE has_status_date_conflict"), ref["status_date_conflicts"]],
        ["Review P0 (one review), all months", ANCHORS["review_p0_all"], q1("SELECT count(*) FROM fact_orders WHERE is_delivered_dated AND review_row_count = 1"), ref["review_p0_all"]],
        ["Reviews dated before delivery, all months", ANCHORS["early_review_all"], q1("SELECT count(*) FROM fact_orders WHERE review_before_delivery_flag"), ref["early_review_all"]],
        ["Sellers with >= 30 / 50 / 100 orders", f"{ANCHORS['sellers_ge30']} / {ANCHORS['sellers_ge50']} / {ANCHORS['sellers_ge100']}",
         "{} / {} / {}".format(*[q1(f"SELECT count(*) FROM (SELECT seller_id FROM v_single_seller_orders GROUP BY 1 HAVING count(*) >= {k})") for k in (30, 50, 100)]),
         f"{ref['sellers_ge30']} / {ref['sellers_ge50']} / {ref['sellers_ge100']}"],
    ]
    rows = [[n, a, d, p, "PASS" if (str(a) == str(d) or a == "n/a (new)") and str(d) == str(p) else "CHECK"] for n, a, d, p in rec]
    w(md_table(["Quantity (exact integers)", "Established anchor", "DuckDB model", "Pandas reference", "Status"], rows))
    lr_duck = late_n / late_d
    lr_pd = ref["late_rate_window"]
    w("\n" + md_table(["Rate", "Anchor", "DuckDB", "Pandas", "abs diff DuckDB vs pandas", "Tolerance check"], [
        ["Calendar late rate, window", "approx. 6.79%", f"{lr_duck:.6f} ({late_n:,}/{late_d:,})", f"{lr_pd:.6f}", f"{abs(lr_duck - lr_pd):.2e}",
         "PASS (abs(rate - 0.0679) < 5e-5; parity < 1e-12)" if abs(lr_duck - 0.0679) < 5e-5 and abs(lr_duck - lr_pd) < 1e-12 else "CHECK"],
        ["Calendar late rate, all months", "6.77%", f"{ANCHORS['late_all'] / ANCHORS['delivered_dated_all']:.6f}", "-", "-", "PASS (6,534/96,470)"],
        ["Severe-late rate, window (> 7 days)", "n/a (new)", f"{q1('SELECT avg(is_severe_late::INT) FROM fact_orders WHERE is_delivery_kpi_eligible'):.6f}",
         f"{ref['severe_late_window'] / ref['delivered_dated_window']:.6f}", "-", "parity PASS"],
        ["Median lead time, window (days)", "n/a (new)", f"{q1('SELECT median(lead_time_days) FROM fact_orders WHERE is_delivery_kpi_eligible'):.6f}", f"{ref['median_lead_window']:.6f}", "-", "parity PASS"],
        ["P95 lead time, window (days)", "n/a (new)", f"{q1('SELECT quantile_cont(lead_time_days, 0.95) FROM fact_orders WHERE is_delivery_kpi_eligible'):.6f}", f"{ref['p95_lead_window']:.6f}", "-", "parity PASS"],
        ["Mean score on-time / late, all months", "4.291 / 2.273",
         "{:.4f} / {:.4f}".format(*[q1(f"SELECT avg(review_score) FROM fact_orders WHERE is_delivered_dated AND review_row_count = 1 AND {c}") for c in ("NOT is_late_calendar", "is_late_calendar")]),
         f"{ref['mean_score_ontime_all']:.4f} / {ref['mean_score_late_all']:.4f}", "-", "PASS (abs tol 5e-4)"],
        ["Mean score on-time / late, window (descriptive, P0)", "n/a (new)",
         "{:.4f} / {:.4f}".format(*[q1(f"SELECT avg(review_score) FROM fact_orders WHERE is_review_kpi_eligible AND {c}") for c in ("NOT is_late_calendar", "is_late_calendar")]),
         f"{ref['mean_score_ontime_window']:.4f} / {ref['mean_score_late_window']:.4f}", "-", "parity PASS"],
    ]))
    w("\nThe window values marked \"new\" are outputs of the model for reconciliation, not analytical findings.\n")

    # ---------------------------------------------------------------- 4 tests
    w("## 4. Automated test results\n")
    w(f"`python -m pytest` result: **{pytest_summary}** (exit code {rc}).\n")
    w(md_table(["Test", "Result", "Seconds"], [[n, s, f"{t:.2f}"] for n, s, t in cases]))
    w(f"\nBuild-time assertions (SQL queries that must return 0 violations), all run on every build:\n")
    w(md_table(["Assertion", "Violations"], [[k, v] for k, v in build_results.items()]))
    w("\nTest design notes: (a) the suite rebuilds the model into a temporary database, so it also tests reproducibility "
      "(a second rebuild is compared frame-by-frame); (b) raw CSV SHA-256 hashes are compared before and after the run; "
      "(c) a deliberate mutation of the lateness rule (`>=` instead of `>`) was confirmed to fail the build assertions "
      "(1,292 violations) during development; (d) pandas parity covers counts, rates, medians, percentiles, scores, "
      "fulfilment classes, distances and the cross-state flag.\n")

    # ---------------------------------------------------------------- 5 data quality
    w("## 5. Data-quality checks on the model (data-quality-auditor)\n")
    w("All figures below were queried from the model; each is a *verified observation*, not an assumption.\n")
    dq = [
        ["Orders without items (all months)", q1("SELECT count(*) FROM fact_orders WHERE n_items = 0"), "Statuses: " + ", ".join(f"{s} {n}" for s, n in q("SELECT order_status, count(*) FROM fact_orders WHERE n_items=0 GROUP BY 1 ORDER BY 2 DESC"))],
        ["Status/delivery-timestamp conflicts", q1("SELECT count(*) FROM fact_orders WHERE has_status_date_conflict"),
         "; ".join(f"{s} -> {c}: {n}" for s, c, n in q("SELECT order_status, fulfilment_class, count(*) FROM fact_orders WHERE has_status_date_conflict GROUP BY 1,2"))],
        ["Timestamp-sequence violations (flagged, retained)", q1("SELECT count(*) FROM fact_orders WHERE ts_sequence_violation"), "Excluded only from carrier-leg metrics (R7)"],
        ["`carrier_leg_unreliable` orders", q1("SELECT count(*) FROM fact_orders WHERE carrier_leg_unreliable"), ""],
        ["Delivered-in-window orders with multiple sellers", q1("SELECT count(*) FROM fact_orders WHERE is_delivery_kpi_eligible AND n_sellers > 1"), "Excluded from seller view"],
        ["Products without category", q1("SELECT count(*) FROM dim_product WHERE is_category_missing"), "Order category 'unknown'/'mixed' rules documented in SQL"],
        ["Categories without English translation", q1("SELECT count(DISTINCT product_category_name) FROM dim_product WHERE is_translation_missing"), "Portuguese name used"],
        ["Orders by `order_category` type", "", ", ".join(f"{k} {v:,}" for k, v in q("SELECT CASE WHEN order_category IN ('mixed','unknown') THEN order_category WHEN order_category IS NULL THEN 'no items' ELSE 'single category' END k, count(*) FROM fact_orders GROUP BY 1 ORDER BY 2 DESC"))],
        ["ZIP prefixes in raw geolocation / kept in `dim_zip_geo`", f"{q1('SELECT count(DISTINCT geolocation_zip_code_prefix) FROM stg_geolocation'):,} / {q1('SELECT count(*) FROM dim_zip_geo'):,}", "Dropped prefixes have only out-of-Brazil points"],
        ["Geolocation points outside the model box / outside the feasibility-style mainland box",
         f"{q1('SELECT count(*) FROM stg_geolocation, model_params p WHERE NOT (geolocation_lat BETWEEN p.geo_lat_min AND p.geo_lat_max AND geolocation_lng BETWEEN p.geo_lng_min AND p.geo_lng_max)')} / {q1('SELECT count(*) FROM stg_geolocation WHERE NOT (geolocation_lat BETWEEN -33.75 AND 5.27 AND geolocation_lng BETWEEN -73.99 AND -34.79)')}",
         "Feasibility report: 42 outside a rough box (matches the second figure)"],
        ["Item rows without distance", q1("SELECT count(*) FROM fact_order_items WHERE distance_km IS NULL"), f"{100 * (1 - q1('SELECT count(*) FROM fact_order_items WHERE distance_km IS NULL') / ANCHORS['items']):.2f}% coverage (feasibility: 99.51%)"],
        ["Negative or zero lead times (delivered-with-date)", q1("SELECT count(*) FROM fact_orders WHERE is_delivered_dated AND lead_time_days <= 0"), ""],
        ["Lead time > 60 days (delivered-with-date, all months)", q1("SELECT count(*) FROM fact_orders WHERE is_delivered_dated AND lead_time_days > 60"), "Retained (feasibility: 306)"],
        ["Review rows per order > 1", q1("SELECT count(*) FROM fact_orders WHERE review_row_count > 1"), "Score deliberately NULL"],
        ["Single-review orders whose review is dated before purchase (all months)", q1("SELECT count(*) FROM fact_orders o JOIN fact_reviews r USING (order_id) WHERE o.review_row_count = 1 AND r.review_creation_date < o.purchase_date"), "Retained; feasibility counted 64 such reviews over all review rows (population differs; not reconciled)"],
    ]
    w(md_table(["Check", "Result", "Note"], dq))
    w("\nJoin-cardinality evidence (row counts before/after each join to `fact_orders`): orders 99,441 -> LEFT JOIN customers 99,441 "
      "-> LEFT JOIN items-by-order 99,441 -> LEFT JOIN reviews-by-order 99,441. Raw orders x items would give 113,425 rows, "
      "orders x reviews 99,992, customers x raw geolocation 15,083,733; the model avoids all three by pre-aggregation "
      "(asserted by `fact_orders rows = stg_orders rows` and by the geolocation test).\n")

    # ---------------------------------------------------------------- 6 SQL review
    w("## 6. SQL review (sql-analytics-reviewer)\n")
    w("Scope: `sql/01_staging.sql`, `02_dimensions.sql`, `03_facts.sql`, and the assertion queries in `scripts/build_model.py`. "
      "Dialect: DuckDB. The model was executed and compared with an independent pandas implementation, so correctness findings "
      "below are empirically verified; performance statements are limited to what was measured.\n")
    w("**Business objective.** Provide an order-grain fact (plus item, review and seller structures) from which the validated KPI "
      "populations can be computed without row multiplication.\n")
    w(md_table(["Severity", "Finding", "Evidence / status"], [
        ["Critical", "None found", f"All {len(cases)} tests and {len(build_results)} build assertions pass; DuckDB and pandas agree to <1e-12 on rates" if rc == 0 else "SEE FAILURES ABOVE"],
        ["Major", "None found", "Join fan-out checks, grain/uniqueness assertions and referential-integrity checks pass"],
        ["Minor", "Lateness comparison relies on `estimated_date` having no time component", "Verified: all source estimates are 00:00:00 (kpi_validation q1); exact-timestamp variant kept only as `is_late_exact` sensitivity"],
        ["Minor", "`is_cross_state` is NULL when an order has several sellers or none", "Intentional; avoids a misleading FALSE"],
        ["Minor", "Raw-path templating (`{{RAW_DIR}}`) means the SQL files are run through `build_model.py`, not stand-alone", "Documented in README"],
        ["Minor", "Build time was measured only informally (a few seconds on the development machine)", "No performance tuning attempted or claimed"],
    ]))
    w("\n**KPI definitions checked.** Late rate = late / delivered-with-date in window (numerator and denominator at order grain, "
      "no divisions inside the model, so no zero-denominator path); lead time = fractional days from purchase to delivery; "
      "promise error = calendar-day difference; severe late = promise error > 7; fulfilment classes partition all orders. "
      "NULL handling: measures are NULL (not zero) when out of population; `review_score` is NULL unless exactly one review row.\n")
    w("**Business interpretation.** The model reproduces the established populations exactly, so it can support the planned "
      "KPIs. It does not by itself resolve the conditional-on-delivery nature of the late rate (blueprint 2.1).\n")

    # ---------------------------------------------------------------- 7 IBGE
    w("## 7. IBGE macro-region mapping (external reference data)\n")
    w("The mapping is **not derived from the dataset**. It is stored in `dim_state` (`sql/02_dimensions.sql`) and was verified "
      "on 2026-10-09 as follows:\n")
    regs = q("SELECT macro_region, string_agg(state_code, ', ' ORDER BY state_code), count(*) FROM dim_state GROUP BY 1 ORDER BY 1")
    w(md_table(["Macro-region", "States", "Count"], [list(r) for r in regs]))
    w("\n- Total: 27 federative units (26 states + the Federal District), each assigned exactly once (test `test_macro_region_mapping`); "
      "every customer and seller state in the dataset maps to a region.\n"
      "- **Sources:** IBGE Quadro Geografico, Grandes Regioes (ibge.gov.br/apps/quadrogeografico, `qg_2023_010_GrandReg.pdf`) via a web "
      "search excerpt, which confirmed Southeast = MG, ES, RJ, SP; South = PR, SC, RS; Central-West = MS, MT, GO, DF; and the five-region "
      "scheme. North and Northeast were confirmed against Wikipedia, \"Regions of Brazil\" (North: AC, AP, AM, PA, RO, RR, TO; "
      "Northeast: AL, BA, CE, MA, PB, PE, PI, RN, SE), which matches the IBGE scheme. I did not open the IBGE PDF directly for "
      "North/Northeast, so those two regions rest on the secondary source plus common knowledge. All five lists are consistent with "
      "one another and with the 7+9+4+4+3 = 27 total.\n"
      "- Use: display grouping only (blueprint 2.5). State names in `dim_state` are stored without diacritics.\n")

    # ---------------------------------------------------------------- 8 deviations
    w("## 8. Deviations from the blueprint and design clarifications\n")
    w(md_table(["#", "Deviation / clarification", "Reason and effect"], [
        [1, "`v_single_seller_orders` contains only **eligible** orders (window + delivered-with-date + one seller; 94,931 rows) rather than every single-seller order",
         "Follows the Phase 1 instruction (\"one row per eligible order\"); blueprint 4.1 described a plain `n_sellers = 1` filter. All single-seller orders remain in `fact_orders` with `is_single_seller`"],
        [2, "Geolocation bounding box eastern bound set to -28.0 (feasibility-style box used -34.79)",
         "Keeps Fernando de Noronha (ZIP 53990). No item in the dataset uses that prefix, so item-level results are unchanged; the effect is documentation correctness"],
        [3, "One more item lacks a distance than the feasibility count (555 vs 554)",
         "One item's customer ZIP (83252) has only two geolocation points with Spanish coordinates; the blueprint rule drops out-of-Brazil points; the feasibility count most likely did not (inference, the feasibility script's centroid step was not re-inspected). Coverage rounds to 99.51% either way"],
        [4, "`fulfilment_class` is assigned to every order regardless of window", "Window membership is a separate flag (`in_window`), so classes can be tabulated for any scope"],
        [5, "Reference date computed as the latest purchase/approval/carrier/delivery timestamp (2018-10-17)", "Blueprint R9 said \"latest timestamp in the extract\"; estimated dates were excluded because they are future promises"],
        [6, "`order_category` = `mixed` also when one item has a missing category next to a known one", "Blueprint wording left this case open; documented in SQL"],
        [7, "Extra columns beyond blueprint 4.2: `delivered_date`, `has_status_date_conflict`, `is_late_exact`, eligibility flags (`is_delivery_kpi_eligible`, `is_seller_kpi_eligible`, `is_review_kpi_eligible`, `is_review_p1_eligible`), `customer_id`", "Make populations explicit and auditable"],
        [8, "Product columns `product_name_lenght`/`product_description_lenght` renamed to `..._length` in `dim_product`", "Fixes source spelling; staging keeps original names"],
        [9, "`dim_state` includes names without diacritics; `dim_date` spans 2016-01-01..2018-12-31", "Convenience; no analytical effect"],
        [10, "`dim_seller` carries `seller_macro_region`", "Convenience for display grouping"],
        [11, "Payments are not modelled", "As designed (blueprint 4.1)"],
        [12, "Post-release fix (found during the delivery-reliability workstream): `ts_sequence_violation` and `carrier_leg_unreliable` are now coalesced to FALSE",
         "They were NULL for orders with missing timestamps and no confirmed violation, so `WHERE NOT ts_sequence_violation` silently dropped 15 delivered and all non-delivered orders. TRUE counts (1,382) and all populations were unchanged; a build assertion and a regression test were added"],
    ]))

    # ---------------------------------------------------------------- 9 issues
    w("\n## 9. Unresolved issues and limitations\n")
    open_not_due = fc.get("open_not_yet_due", 0)
    w(f"- **No open order is \"not yet due\" in the window** ({open_not_due:,}); every open-status order in the window is past its promise at the reference date, "
      "consistent with the blueprint's hypothesis that these orders are stalled or abandoned in the data. The cause is not verified.\n"
      "- **Conditional-on-delivery late rate:** unchanged from blueprint 2.1; this phase builds the populations, it does not resolve selection.\n"
      "- **Time zones** of source timestamps remain undocumented; calendar-date lateness assumes dates are comparable.\n"
      "- **Timestamp anomalies** (1,382 orders) are flagged, not explained.\n"
      "- **Multi-review orders** (547) remain ambiguous by design; no score is assigned.\n"
      "- **Anchor coverage:** anchors cover the populations and counts established in earlier reports; the window late *count* (6,531) and window review counts are new numbers verified only by the independent pandas implementation, not by a third source.\n"
      "- **Provisional minimum of 20 excess late orders** (Investigate tier) is not implemented; tiers are out of scope for Phase 1.\n"
      "- **External reference data:** IBGE mapping rests on one primary-source excerpt (3 regions) and one secondary source (all 5); see section 7.\n"
      "- **Environment:** developed on Python 3.14, DuckDB 1.5.x, pandas 3.0.x; older versions were not tested.\n"
      "- **Geography:** centroid distance is straight-line between ZIP-prefix medians, not road distance; 278 customer and 7 seller prefixes have no geolocation row in the raw file.\n")

    # ---------------------------------------------------------------- 10 reproducibility
    w("## 10. Reproducibility\n")
    w("Rebuild instructions are in `README.md`. Quick version (from the project root):\n\n"
      "```\npip install -r requirements.txt\npython scripts/build_model.py\npython -m pytest\npython scripts/build_validation_report.py\n```\n")
    w("Raw file fingerprints (SHA-256, first 16 hex characters) at report time:\n")
    w(md_table(["File", "Bytes", "SHA-256 (prefix)"], [[p.name, p.stat().st_size, hashlib.sha256(p.read_bytes()).hexdigest()[:16]] for p in sorted(RAW.glob("*.csv"))]))

    OUT.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT} (pytest exit code {rc})")
    return rc


if __name__ == "__main__":
    sys.exit(main())
