"""Render reports/dataset_feasibility.md from reports/profile_stats.json.

Every number in the report is interpolated from the JSON, so the report cannot
drift from the computed statistics.
Usage: python scripts/build_feasibility_report.py  (after profile_dataset.py)
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
s = json.loads((ROOT / "reports" / "profile_stats.json").read_text(encoding="utf-8"))
T, R, D, F = s["tables"], s["relationships"], s["orders_profile"], s["feasibility_inputs"]


def n(x: int) -> str:
    return f"{x:,}"


def key_str(t: str) -> str:
    out = []
    for k in T[t]["keys"]:
        out.append(f"`{'+'.join(k['key'])}` {'unique' if k['unique'] else 'NOT unique'}")
    return "; ".join(out)


def miss_str(t: str) -> str:
    m = [f"`{c}` {x['missing_pct']}%" for c, x in T[t]["columns"].items() if x["missing"]]
    return ", ".join(m) if m else "none"


schema_rows = "\n".join(
    f"| {t} | {n(v['rows'])} | {v['n_cols']} | {n(v['full_duplicate_rows'])} | {key_str(t)} | {miss_str(t)} |"
    for t, v in T.items()
)
st = D["status_counts"]
status_str = ", ".join(f"{k} {n(v)} ({D['status_pct'][k]}%)" for k, v in st.items())
tm = D["timestamp_missing"]
dd = D["delivery_days_describe"]
ob = R["orders_without_items_by_status"]
ob_str = ", ".join(f"{k} {n(v)}" for k, v in ob.items())
rs = R["review_score_counts"]
low_pct = round(100 * (rs["1"] + rs["2"]) / sum(rs.values()), 1)

report = f"""# Olist Dataset Profiling and Feasibility Report

Generated by `scripts/profile_dataset.py` + `scripts/build_feasibility_report.py` from `data/raw/` (source CSVs read-only, unmodified). All figures are computed; the raw statistics are in `reports/profile_stats.json`.

## 1. Schema summary

| Table | Rows | Cols | Full-duplicate rows | Candidate keys | Columns with missing values |
|---|---:|---:|---:|---|---|
{schema_rows}

Data types: all IDs, categories and timestamps load as strings (timestamps parsed explicitly in the script); counts, prices, weights and coordinates are numeric. Product column names `product_name_lenght` / `product_description_lenght` are misspelt in the source.

## 2. Key findings

### Grain and join cardinality
- **orders** is unique on `order_id` ({n(T['orders']['rows'])} orders). `customer_id` is one-per-order; `customer_unique_id` identifies the person: {n(R['customers_unique_ids'])} unique people, of whom {n(R['unique_customers_with_multiple_customer_ids'])} have more than one `customer_id` (repeat buyers). No orphan references in orders↔customers, items→orders/products/sellers.
- **order_items** (1 order → many items): {n(R['orders_with_multiple_items'])} orders have >1 item (max {R['max_items_per_order']}). Joining orders to items yields {n(R['row_multiplication_orders_x_items'])} rows vs {n(T['orders']['rows'])} orders. **{n(R['orders_without_items'])} orders have no items** ({ob_str}).
- **Multi-seller orders:** {n(R['orders_with_multiple_sellers'])} orders ({F['orders_multi_seller_pct_of_items_orders']}% of orders with items) involve more than one seller.
- **payments** (1 order → many rows): {n(R['orders_with_multiple_payment_rows'])} orders have multiple payment rows; orders×payments gives {n(R['row_multiplication_orders_x_payments'])} rows. {R['orders_without_payments']} order has no payment; {R['payment_value_zero_rows']} payment rows have value 0. Payment total differs from items+freight by more than 1 BRL in {n(R['orders_payment_vs_items_gap_gt_1'])} of {n(R['orders_compared_payment_vs_items'])} comparable orders (vouchers/instalment interest likely, not verified).
- **reviews** (1 order → 0..many): `review_id` is not unique and `order_id` is not unique; (`review_id`,`order_id`) is. {n(R['orders_with_multiple_reviews'])} orders have multiple reviews and {n(R['orders_without_reviews'])} have none; orders×reviews gives {n(R['row_multiplication_orders_x_reviews'])} rows. Only {n(R['reviews_with_comment_text'])} reviews contain comment text.
- **geolocation is not a lookup table:** {n(R['geo_rows'])} rows for {n(R['geo_unique_zip_prefixes'])} ZIP prefixes; {n(T['geolocation']['full_duplicate_rows'])} rows are exact duplicates. {n(R['geo_prefixes_with_multiple_rows'])} prefixes have several rows (median {R['geo_median_rows_per_prefix']:.0f}, max {n(R['geo_max_rows_per_prefix'])}); {n(R['geo_prefixes_with_multiple_distinct_coords'])} have more than one distinct coordinate pair, {n(R['geo_prefixes_with_multiple_city_spellings'])} have multiple city spellings and {R['geo_prefixes_with_multiple_states']} span more than one state. A raw join of customers to geolocation yields {n(R['row_multiplication_customers_x_geo_raw'])} rows (vs {n(R['customers_rows'])} customers) — it must be aggregated to one row per prefix first. {R['geo_coords_outside_brazil_bbox']} coordinates fall outside a rough Brazil bounding box. {n(R['customer_zip_not_in_geo'])} customer and {R['seller_zip_not_in_geo']} seller ZIP prefixes are absent from geolocation.
- **products:** {R['products_missing_category']} products lack a category (and name/description/photo fields); {R['categories_without_translation']} categories have no English translation; {R['product_missing_dimensions']} products miss weight/dimensions, {R['product_zero_weight']} have zero weight.

### Order status and timestamps
- Status: {status_str}.
- Missing timestamps: approved {n(tm['order_approved_at'])}, carrier handoff {n(tm['order_delivered_carrier_date'])}, customer delivery {n(tm['order_delivered_customer_date'])}; purchase and estimated-delivery are 100% complete. No unparseable values.
- Status/timestamp inconsistencies: {D['delivered_status_missing_customer_date']} `delivered` orders lack a delivery date; {D['non_delivered_with_customer_date']} non-delivered orders have one; {D['delivered_status_missing_approved']} delivered orders lack an approval time.
- Invalid sequences: carrier date before purchase {D['carrier_before_purchase']}, carrier before approval {n(D['carrier_before_approved'])}, customer delivery before carrier handoff {D['customer_before_carrier']}; approval/delivery before purchase and estimate before purchase: 0. {n(D['any_sequence_violation_checked_pairs'])} orders have at least one violation.
- Delivered orders with a delivery date: {n(D['delivered_with_both_dates'])}. Purchase→delivery days: median {dd['50%']}, mean {dd['mean']}, p95 {dd['95%']}, p99 {dd['99%']}, max {dd['max']}; {D['delivery_days_gt_60']} exceed 60 days. Median promised lead time is {D['estimated_days_median']} days. **{D['late_pct_delivered']}%** of delivered orders arrived after the estimate.
- Coverage: purchases span {D['months_span'][0]} to {D['months_span'][1]} ({D['months_total']} calendar months). Zero orders in {', '.join(D['months_with_zero_orders'])}; fewer than 100 orders in {', '.join(D['months_lt_100_orders'])} (partial/ramp-up months). Peak month {D['peak_month']['month']} ({n(D['peak_month']['orders'])} orders).

### Geography and sellers
- Customers are concentrated: SP is {R['order_share_top_state']['pct']}% of orders and SP+RJ+MG {R['order_share_sp_rj_mg']}%. {R['seller_share_sp']}% of sellers are in SP; sellers cover {R['seller_states']} states vs {R['customer_states']} for customers. {F['same_state_item_pct']}% of item rows are same-state shipments.
- {n(F['sellers_with_delivered_orders'])} sellers have delivered orders; {n(F['sellers_ge_10_delivered_orders'])} have ≥10, {n(F['sellers_ge_30_delivered_orders'])} have ≥30 and {n(F['sellers_ge_100_delivered_orders'])} have ≥100. The top 10% of sellers account for {F['top_10pct_sellers_share_of_seller_orders']}% of seller-order pairs.

### Reviews
- Score distribution: {', '.join(f'{k}★ {n(v)}' for k, v in rs.items())} ({low_pct}% are 1–2★). {D['delivered_orders_with_review_pct']}% of delivered orders have a review.
- Timing anomalies: {n(D['reviews_created_before_delivery'])} reviews were created before the recorded delivery date, {D['reviews_created_before_purchase']} before the purchase date, and {n(D['reviews_for_undelivered_orders'])} belong to non-delivered orders.
- Descriptive only (no causal claim): mean score is {D['mean_score_on_time']} for on-time vs {D['mean_score_late']} for late delivered orders.

## 3. Feasibility assessment

| Analysis | Feasible? | Basis | Main risks |
|---|---|---|---|
| Delivery performance (actual vs estimated, lead time) | **Yes** | {n(D['delivered_with_both_dates'])} delivered orders with complete purchase/estimate/delivery timestamps | Right-censoring: undelivered orders excluded; {n(D['any_sequence_violation_checked_pairs'])} orders with inconsistent intermediate timestamps (use purchase→customer delivery only); long-tail outliers |
| Regional comparison (customer state) | **Yes** (state level); city/ZIP weak | All 27 customer states present; no orphan customers | Heavy SP/RJ/MG concentration → small samples in northern states; need minimum-N rules |
| Seller-level analysis | **Partly** | {n(F['sellers_ge_30_delivered_orders'])} sellers with ≥30 delivered orders | Long-tailed volume; {n(R['orders_with_multiple_sellers'])} multi-seller orders make order-level delay/review ambiguous to attribute (delivery dates are order-level, not item/seller-level) |
| Customer review analysis | **Yes** (scores); text limited | {n(sum(rs.values()))} reviews | Self-selection (reviews are voluntary); multiple reviews per order; only {n(R['reviews_with_comment_text'])} with text (Portuguese); timing anomalies; review reflects whole order, not one seller |
| Approximate distance (seller↔customer) | **Yes, approximate** | {F['item_rows_with_both_zip_centroids_pct']}% of item rows have ZIP centroids for both parties | Centroid from a non-unique prefix table (median within-prefix coordinate SD ≈ {F['geo_zip_median_coord_sd_km']} km, rough); straight-line not road distance; 5-digit prefixes only; multi-seller orders need item-level distance |
| Causal claims (e.g. lateness → low score) | **No** | Observational | Confounding (product, region, seller), selection into reviewing |

## 4. Limitations and bias risks
- **Selection/survivorship:** delivery metrics cover only delivered orders ({D['delivered_orders']:,} of {n(D['orders'])}); canceled/unavailable orders ({n(D['canceled_or_unavailable'])}) are invisible to delivery KPIs. Orders ending the window (2018-09/10) may be incompletely observed.
- **Attribution:** order-level timestamps and review scores cannot be assigned to a single seller when an order has several; recommend excluding or flagging multi-seller orders in seller scorecards.
- **Reviews:** voluntary and skewed positive; customers with bad experiences may be more (or less) likely to respond — direction is not identifiable from this data.
- **Window and representativeness:** one marketplace, 2016-09 to 2018-10, with an apparent ramp-up; company-wide conclusions should not be drawn; whether the data is a full or sampled population cannot be determined from the files.
- **Not verified:** payment/item gaps, causes of timestamp inversions, and whether late 2018 months are truncated by extraction date.

## 5. Recommended next steps
1. Build a cleaned order-grain fact table: aggregate payments and reviews to one row per order (latest review, flag duplicates) *before* joining; keep item-grain table separately for seller/product analysis.
2. Build a one-row-per-ZIP-prefix geolocation table (median lat/lng after de-duplication, drop out-of-bounds points) and compute haversine distance at item level.
3. Define rules for timestamp anomalies (flag, do not delete) and a minimum-sample threshold for region/seller comparisons.
4. Restrict trend analyses to complete months (exclude {', '.join(D['months_lt_100_orders'])} or mark them partial).
5. Then proceed to EDA, KPI definitions (on-time rate, lead time, review score) and modelling/dashboard scoping.
"""
(ROOT / "reports" / "dataset_feasibility.md").write_text(report, encoding="utf-8")
print("wrote reports/dataset_feasibility.md;", len(report.split()), "words")
