"""Generate reports/delivery_reliability_findings.md from the outputs of analysis/delivery_reliability.py.

Usage: python analysis/delivery_reliability.py && python analysis/build_delivery_report.py
Numbers are interpolated from reports/delivery_reliability_stats.json and reports/tables/delivery_*.csv.
Qualitative statements are guarded by assertions (see `check_claims`): if the data change so that a claim
no longer holds, the build fails instead of publishing stale narrative.
"""
from __future__ import annotations

import json
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
STATS = json.loads((ROOT / "reports" / "delivery_reliability_stats.json").read_text(encoding="utf-8"))
T = {p.stem.replace("delivery_", "", 1): pd.read_csv(p) for p in (ROOT / "reports" / "tables").glob("delivery_*.csv")}
OUT = ROOT / "reports" / "delivery_reliability_findings.md"
JUNIT = ROOT / "data" / "processed" / "pytest_junit_delivery.xml"


def pct(x, d=2):
    return f"{100 * x:.{d}f}%"


def n(x):
    return f"{int(round(x)):,}"


def ci(lo, hi, d=2):
    return f"[{pct(lo, d)}, {pct(hi, d)}]"


def md(df: pd.DataFrame, headers: list[str]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join("---" for _ in headers) + "|"]
    lines += ["| " + " | ".join(str(c) for c in r) + " |" for r in df.itertuples(index=False)]
    return "\n".join(lines)


def run_pytest() -> tuple[int, str, list[tuple[str, str]]]:
    proc = subprocess.run([sys.executable, "-m", "pytest", "-q", f"--junitxml={JUNIT}"], cwd=ROOT, capture_output=True, text=True)
    cases = []
    for tc in ET.parse(JUNIT).getroot().iter("testcase"):
        bad = tc.find("failure") is not None or tc.find("error") is not None
        cases.append((f"{tc.get('classname', '').split('.')[-1]}::{tc.get('name')}", "FAIL" if bad else "PASS"))
    return proc.returncode, proc.stdout.strip().splitlines()[-1], cases


def check_claims(m: pd.DataFrame, pg: pd.DataFrame) -> dict:
    """Assert the qualitative statements used in the narrative; return derived figures."""
    m = m.copy()
    top3 = m.sort_values("late_rate", ascending=False).head(3)
    assert set(top3.purchase_month) == {"2017-11-01", "2018-02-01", "2018-03-01"}, "top-3 late months changed"
    assert m.loc[m.late_rate.idxmin(), "purchase_month"] == "2018-06-01"
    assert (top3.late_rate_lo > m[~m.purchase_month.isin(top3.purchase_month)].late_rate_hi.max()).all(), "top-3 not clearly separated"
    rest = m[~m.purchase_month.isin(top3.purchase_month)]
    d = {
        "top3_late_share": top3.n_late.sum() / m.n_late.sum(),
        "top3_delivered_share": top3.n_delivered.sum() / m.n_delivered.sum(),
        "rest_rate": rest.n_late.sum() / rest.n_delivered.sum(),
        "rest_min": rest.late_rate.min(), "rest_max": rest.late_rate.max(),
        "top3_months": list(top3.purchase_month.str[:7]),
    }
    assert pg.late_rate.iloc[0] < pg.late_rate.iloc[2], "shortest promise group no longer below 22-28 day group"
    assert pg.late_rate.iloc[-1] == pg.late_rate.min(), "36+ day group no longer lowest"
    assert m.expected_rate.iloc[3:].max() - m.expected_rate.iloc[3:].min() < 0.02, "expected rate no longer flat"
    fm = T["fulfilment_monthly"]
    epi = fm[fm.purchase_month.isin(["2017-11-01", "2018-02-01", "2018-03-01"])]
    oth = fm[~fm.purchase_month.isin(epi.purchase_month)]
    assert (epi.open_past_promise_share.max() < oth.open_past_promise_share.max()
            and epi.cancelled_unavailable_share.max() < oth.cancelled_unavailable_share.max()), \
        "open/cancelled shares now peak in the late-rate episodes; revise the narrative"
    return d


def main() -> int:
    rc, pytest_summary, cases = run_pytest()
    m, pg, sens = T["monthly"], T["promise_groups"], T["sensitivity"]
    fm, sc = T["fulfilment_monthly"], T["scenario_monthly"]
    o, lo_, ps = STATS["overall"], STATS["lead_overall"], STATS["promise_summary"]
    sl, hv, pk = STATS["severity_among_late"], STATS["high_volume"], STATS["peak_vs_neighbours"]
    ft, sb = STATS["fulfilment_total"], STATS["scenario_bounds"]
    d = check_claims(m, pg)
    sev = T["severity_bands"].set_index("days_late_band").n_orders
    first, last = m.iloc[0], m.iloc[-1]
    jul = m[m.purchase_month == "2018-07-01"].iloc[0]
    st = T["status_by_class"]
    base_row = sens.iloc[0]

    w = []
    A = w.append
    A("# Delivery Reliability: Findings (Workstream 1)\n")
    A("Generated by `analysis/build_delivery_report.py` from `analysis/delivery_reliability.py` (SQL in `sql/analysis/delivery/`) "
      "on the validated DuckDB model. Everything below is **descriptive and observational**: it shows how delivery outcomes vary, "
      "not why. No seller, geographic, satisfaction or predictive analysis is included.\n")
    A("Labels: **[Observed]** a computed result; **[Interpretation]** a reading of the result that goes beyond it; "
      "**[Hypothesis]** a possible explanation this analysis cannot test.\n")

    # ------------------------------------------------------------------ 1
    A("## 1. Populations and KPI definitions\n")
    A(f"- **Delivered-only population (delivery KPIs):** orders with status `delivered` and a customer-delivery timestamp, purchased 2017-01 to 2018-08: "
      f"**N = {n(o['n_delivered'])}** (the established model population `is_delivery_kpi_eligible`; nothing was redefined).\n"
      f"- **All-order population (fulfilment outcomes):** every order purchased in the same window: **N = {n(ft['n_orders'])}**. "
      "Delivered-only KPIs and all-order outcomes are reported separately and never blended.\n"
      f"- Reference date for 'past promise': {STATS['reference_date']} (latest observed event timestamp in the extract).\n")
    A(md(pd.DataFrame([
        ["Late-delivery rate", "`DATE(delivered) > estimated date` / delivered-only orders", "Calendar-date rule; Wilson 95% intervals"],
        ["Severe-late rate", "promise error > 7 calendar days / delivered-only orders", "Equals band '8+' (> 7 days late)"],
        ["Lead time", "purchase timestamp to customer-delivery timestamp, fractional days; median, p90, p95", "Seeded bootstrap 95% intervals (orders resampled independently)"],
        ["Promise error", "`DATE(delivered) - estimated date`, signed days; negative = early", "Promise slack = -error for on-time orders"],
        ["Promised lead time", "estimated date - purchase date, days", "Groups fixed before looking at outcomes: <=14, 15-21, 22-28, 29-35, 36+"],
        ["Fulfilment class share", "class count / all window orders", "Six mutually exclusive classes (blueprint R9)"],
        ["High-volume month", "top 5 of 20 cohort months by delivered-order count (top quartile)", "Rule fixed in advance"],
        ["Expected late rate", "month's orders x pooled late rate of their promised-lead group", "Indirect standardisation; observed/expected = O/E"],
    ]), ["KPI", "Definition", "Notes"]) + "\n")

    # ------------------------------------------------------------------ 2
    A("## 2. Headline results\n")
    A(md(pd.DataFrame([
        ["Late-delivery rate (calendar date)", f"{pct(o['late_rate'])} ({n(o['n_late'])} / {n(o['n_delivered'])})", ci(*o['late_ci'])],
        ["Severe-late rate (> 7 days)", f"{pct(o['severe_rate'])} ({n(o['n_severe'])})", ci(*o['severe_ci'])],
        ["Severe orders as share of late orders", pct(o['severe_share_of_late'], 1), ""],
        ["Median lead time", f"{lo_['median']:.2f} days", f"[{lo_['median_ci'][0]:.2f}, {lo_['median_ci'][1]:.2f}]"],
        ["p90 lead time", f"{lo_['p90']:.2f} days", f"[{lo_['p90_ci'][0]:.2f}, {lo_['p90_ci'][1]:.2f}]"],
        ["p95 lead time", f"{lo_['p95']:.2f} days", f"[{lo_['p95_ci'][0]:.2f}, {lo_['p95_ci'][1]:.2f}]"],
        ["Median promised lead time", f"{ps['promised_lead_median']:.0f} days", ""],
        ["Late rate by exact timestamp (sensitivity only)", pct(o['n_late_exact'] / o['n_delivered']), "Counts any delivery after midnight of the promised day"],
    ]), ["Measure", "Value", "95% interval"]) + "\n")
    A(f"**[Observed]** About {pct(o['late_rate'], 1)} of delivered orders arrive after the promised calendar date and {pct(o['severe_rate'], 1)} arrive more than a week late. "
      f"The pooled rate hides large month-to-month variation: cohort rates range from {pct(o['late_rate_min_month'], 1)} to {pct(o['late_rate_max_month'], 1)} (Section 3).\n")

    # ------------------------------------------------------------------ 3
    A("## 3. Late rate by purchase-month cohort\n")
    A("![Monthly late rate](figures/delivery_01_monthly_late_rate.png)\n")
    mt = pd.DataFrame({
        "Cohort": m.purchase_month.str[:7], "Delivered": m.n_delivered.map(n), "Late": m.n_late.map(n),
        "Late rate [95% Wilson]": [f"{pct(r)} {ci(a, b)}" for r, a, b in zip(m.late_rate, m.late_rate_lo, m.late_rate_hi)],
        "Severe rate": m.severe_rate.map(pct), "Median / p90 / p95 lead (d)": [f"{a:.1f} / {b:.1f} / {c:.1f}" for a, b, c in zip(m.lead_median, m.lead_p90, m.lead_p95)],
        "Median promise (d)": m.promised_lead_median.map(lambda v: f"{v:.0f}"), "O/E": m.oe_ratio.map(lambda v: f"{v:.2f}"),
        "Mature at 60 d": m.mature_60d.map(lambda v: "yes" if v else "no"),
    })
    A(md(mt, list(mt.columns)) + "\n")
    A(f"**[Observed]** Three cohorts stand well apart from the rest: {', '.join(d['top3_months'])}. Their rates are clearly separated (Wilson lower bounds above every other month's upper bound). "
      f"Together they hold {pct(d['top3_delivered_share'], 1)} of delivered orders but {pct(d['top3_late_share'], 1)} of all late orders. "
      f"The other 17 cohorts together have a late rate of {pct(d['rest_rate'])} (individual months {pct(d['rest_min'], 1)} to {pct(d['rest_max'], 1)}).\n")
    A(f"**[Observed]** The lowest cohort is 2018-06 ({pct(m.loc[m.late_rate.idxmin(), 'late_rate'])}). From 2018-07 to 2018-08 the late rate rises again "
      f"({pct(jul.late_rate)} to {pct(last.late_rate)}) while the severe rate stays near 1% ({pct(jul.severe_rate)} to {pct(last.severe_rate)}).\n")
    A("**[Interpretation]** Delivery lateness in this data is episodic rather than steady: a few cohorts drive roughly half of all late deliveries. "
      "The cause of those episodes is not identifiable from these data **[Hypothesis]**: demand peaks, carrier or capacity problems and changes to promise setting are all candidates.\n")

    # ------------------------------------------------------------------ 4
    A("## 4. Lead time\n")
    A("![Lead time by month](figures/delivery_02_lead_time_by_month.png)\n")
    A(f"**[Observed]** Overall median lead time is {lo_['median']:.1f} days, p90 {lo_['p90']:.1f} and p95 {lo_['p95']:.1f}. Cohort medians range from "
      f"{m.lead_median.min():.1f} to {m.lead_median.max():.1f} days. The slow tail follows the late-rate episodes: p95 peaks at {m.lead_p95.max():.1f} days "
      f"({m.loc[m.lead_p95.idxmax(), 'purchase_month'][:7]}). After the 2018-03 peak, median and p95 fall cohort by cohort: the 2018-08 cohort has median {last.lead_median:.1f} and p95 {last.lead_p95:.1f} days.\n")
    A("**[Interpretation]** The fall in 2018-07/08 is partly uncertain: the latest cohorts have had only 47 to 77 days (2018-08 purchases) to be delivered before the extract ended, "
      "so the slowest orders may not yet be observed. This cannot explain the decline in the *median* (which is driven by ordinary deliveries), but it could contribute to the p95/p90 decline in the last cohorts. "
      "Bootstrap intervals treat orders as independent, so they understate uncertainty from clustering by customer.\n")

    # ------------------------------------------------------------------ 5
    A("## 5. Promise error and earliness\n")
    A("![Promise error](figures/delivery_03_promise_error_distribution.png)\n")
    A(f"**[Observed]** The median order arrives **{abs(ps['error_p50']):.0f} days before** the promised date (p25 {ps['error_p25']:.0f}, p75 {ps['error_p75']:.0f}; p5 {ps['error_p05']:.0f}, p95 {ps['error_p95']:.0f}). "
      f"{pct(ps['n_before_promised_day'] / ps['n_delivered'], 1)} of delivered orders arrive before the promised day, {pct(ps['n_on_promised_day'] / ps['n_delivered'], 1)} on it, "
      f"{pct(ps['n_7plus_days_early'] / ps['n_delivered'], 1)} at least 7 days early and {pct(ps['n_14plus_days_early'] / ps['n_delivered'], 1)} at least 14 days early. "
      f"Among on-time orders the median slack is {ps['slack_median_on_time']:.0f} days (interquartile range {ps['slack_p25_on_time']:.0f} to {ps['slack_p75_on_time']:.0f}). "
      f"The median order takes {pct(ps['lead_to_promise_ratio_median'], 0)} of its promised lead time.\n")
    A("**[Interpretation]** Estimated delivery dates carry a large buffer for typical orders. The same buffer is not enough in the episodic late cohorts: the promised-lead mix was stable "
      f"across months (expected late rate given the mix stays between {pct(m.expected_rate.iloc[3:].min(), 1)} and {pct(m.expected_rate.iloc[3:].max(), 1)} from 2017-04 onward, Figure 6), "
      "so promises did not become more conservative when deliveries slowed.\n")

    # ------------------------------------------------------------------ 6
    A("## 6. Severe lateness (> 7 calendar days late)\n")
    A(md(pd.DataFrame([
        ["1-3 days late", n(sev['1-3']), pct(sev['1-3'] / o['n_delivered'])],
        ["4-7 days late", n(sev['4-7']), pct(sev['4-7'] / o['n_delivered'])],
        ["8+ days late (severe)", n(sev['8+']), pct(sev['8+'] / o['n_delivered'])],
    ]), ["Band", "Orders", "Share of delivered"]) + "\n")
    A(f"**[Observed]** Late orders are a mix of shallow and deep delays: the median late order is {sl['days_late_median']:.0f} days late, p90 is {sl['days_late_p90']:.0f} days, "
      f"and {pct(o['severe_share_of_late'], 1)} of late orders are severe (maximum {sl['days_late_max']:.0f} days). The severe-late rate follows the same cohort pattern as the late rate "
      f"(peak {pct(m.severe_rate.max(), 1)} in {m.loc[m.severe_rate.idxmax(), 'purchase_month'][:7]}).\n")

    # ------------------------------------------------------------------ 7
    A("## 7. All-order fulfilment outcomes (separate from delivered-only KPIs)\n")
    A("![Fulfilment outcomes](figures/delivery_04_fulfilment_outcomes.png)\n")
    cls = [("delivered_on_time", "Delivered on time"), ("delivered_late", "Delivered late"), ("cancelled_unavailable", "Cancelled / unavailable"),
           ("open_past_promise", "Open (non-terminal status), past promised date"), ("open_not_yet_due", "Open, not yet due"),
           ("delivered_status_no_date", "Status delivered, no delivery date")]
    A(md(pd.DataFrame([[lab, n(ft[c]), pct(ft[c] / ft['n_orders'])] for c, lab in cls]), ["Outcome class", "Orders", "Share of all window orders"]) + "\n")
    stat_open = st[st.fulfilment_class == "open_past_promise"]
    stat_can = st[st.fulfilment_class == "cancelled_unavailable"]
    A("Original statuses behind the unresolved classes: open past promise: " + ", ".join(f"{r.order_status} {n(r.n_orders)}" for r in stat_open.itertuples())
      + "; cancelled/unavailable: " + ", ".join(f"{r.order_status} {n(r.n_orders)}" for r in stat_can.itertuples()) + ".\n")
    A(f"**[Observed]** {pct((ft['cancelled_unavailable'] + ft['open_past_promise']) / ft['n_orders'], 1)} of window orders ({n(ft['cancelled_unavailable'] + ft['open_past_promise'])}) never reached a delivered state by the extract date: "
      f"{n(ft['cancelled_unavailable'])} cancelled or unavailable and {n(ft['open_past_promise'])} still in an open status although the promised date had passed. "
      f"No window order is open and not yet due. Monthly shares stay between {pct(fm.cancelled_unavailable_share.min(), 1)} and {pct(fm.cancelled_unavailable_share.max(), 1)} "
      f"(cancelled/unavailable, highest in {fm.loc[fm.cancelled_unavailable_share.idxmax(), 'purchase_month'][:7]}) and between {pct(fm.open_past_promise_share.min(), 1)} and "
      f"{pct(fm.open_past_promise_share.max(), 1)} (open past promise, highest in {fm.loc[fm.open_past_promise_share.idxmax(), 'purchase_month'][:7]}); "
      "neither shows the spikes seen in the late rate in 2017-11, 2018-02 and 2018-03.\n")
    A("**Unresolved orders are not confirmed failures.** An open status at the extract date does not show that delivery failed: the data cannot distinguish stalled shipments from orders "
      "whose status was never updated, and cancelled orders were never expected to be delivered. The illustrative scenario below only shows how sensitive the delivered-only late rate is to what those open orders might be; it is **not an estimate**.\n")
    A(md(pd.DataFrame([
        ["No open past-promise order was late", pct(sb['late_rate_if_no_open_order_late'])],
        ["Observed (delivered-only)", pct(sb['late_rate_observed_delivered_only'])],
        ["Every open past-promise order was late (extreme bound)", pct(sb['late_rate_if_all_open_orders_late'])],
    ]), ["Scenario for the 1,699 open orders (cancelled/unavailable excluded)", "Late rate"]) + "\n")
    A("**[Interpretation]** The delivered-only rate is a conditional observed rate. Whatever happened to the open orders, the rate over delivered plus open orders would lie between "
      f"{(sb['late_rate_observed_delivered_only'] - sb['late_rate_if_no_open_order_late']) * 100:.1f} points below and "
      f"{(sb['late_rate_if_all_open_orders_late'] - sb['late_rate_observed_delivered_only']) * 100:.1f} points above the observed rate; the upper figure rests on an extreme assumption. "
      "The direction and size of any real difference are unknown.\n")

    # ------------------------------------------------------------------ 8
    A("## 8. Do high-volume months and promised-lead groups differ in observed late rate?\n")
    A("### 8.1 High-volume purchase months\n")
    A("![Observed vs expected](figures/delivery_06_observed_vs_expected.png)\n")
    A(md(pd.DataFrame([
        [f"High-volume ({', '.join(x[:7] for x in hv['months'])})", n(hv['n_high']), n(hv['late_high']), f"{pct(hv['rate_high'])} {ci(*hv['rate_high_ci'])}", f"{hv['oe_high']:.2f}"],
        ["Other 15 months", n(hv['n_other']), n(hv['late_other']), f"{pct(hv['rate_other'])} {ci(*hv['rate_other_ci'])}", f"{hv['oe_other']:.2f}"],
    ]), ["Group", "Delivered", "Late", "Late rate [95% Wilson]", "O/E given promised mix"]) + "\n")
    A(f"**[Observed]** High-volume months have a higher pooled late rate ({pct(hv['rate_high'], 1)} vs {pct(hv['rate_other'], 1)}; difference {hv['diff'] * 100:.1f} points, "
      f"Newcombe 95% interval {hv['diff_ci'][0] * 100:.1f} to {hv['diff_ci'][1] * 100:.1f}). Peak month 2017-11 ({n(pk['peak_n'])} delivered orders) had {pct(pk['peak_rate'], 1)} late versus "
      f"{pct(pk['neighbour_rate'], 1)} in the adjacent months 2017-10 and 2017-12 (difference {pk['diff'] * 100:.1f} points, interval {pk['diff_ci'][0] * 100:.1f} to {pk['diff_ci'][1] * 100:.1f}). "
      f"Across the 20 cohorts, monthly volume and late rate are moderately rank-correlated (Spearman {hv['spearman_volume_vs_rate_all']:.2f}).\n")
    hvm = m[m.high_volume].sort_values("purchase_month")
    hv_detail = "the five months' late rates are " + ", ".join(f"{r.purchase_month[:7]} {pct(r.late_rate, 1)}" for r in hvm.itertuples()) + "."
    A("**[Interpretation]** The volume pattern is an association with limited evidential weight. (a) The intervals treat orders as independent; the unit that varies is the month (n = 20), "
      "so they are too narrow for a month-level claim. (b) Volume rose steadily over the window, so it is confounded with calendar time and marketplace growth. "
      "(c) The high-volume group is heterogeneous: " + hv_detail + " "
      "Months with similar volume (2018-06 to 2018-08) had very different late rates, and 2018-02, the second-highest late rate, is not in the high-volume group. Volume alone does not explain the episodes. "
      "(d) The promised-lead mix does not explain them either: the expected rate given that mix is flat at about 7% while observed monthly rates range from 1% to 19%. "
      "All of this is association; no mechanism is tested.\n")
    A("### 8.2 Promised lead-time groups\n")
    A("![Promised lead groups](figures/delivery_05_promised_lead_groups.png)\n")
    pt = pd.DataFrame({
        "Promised lead": pg.promised_group.str.split(": ").str[1], "Delivered": pg.n_delivered.map(n),
        "Late rate [95% Wilson]": [f"{pct(r)} {ci(a, b)}" for r, a, b in zip(pg.late_rate, pg.late_rate_lo, pg.late_rate_hi)],
        "Severe rate [95% Wilson]": [f"{pct(r)} {ci(a, b)}" for r, a, b in zip(pg.severe_rate, pg.severe_rate_lo, pg.severe_rate_hi)],
        "Median lead (d)": pg.lead_median.map(lambda v: f"{v:.1f}"), "Median promise error (d)": pg.promise_error_median.map(lambda v: f"{v:.0f}"),
    })
    A(md(pt, list(pt.columns)) + "\n")
    dd = STATS["promise_group_diff_shortest_vs_longest"]
    A(f"**[Observed]** The late rate is **not monotone** in promised lead time: it is {pct(pg.late_rate.iloc[0], 1)} for the shortest promises (<=14 days), peaks at {pct(pg.late_rate.max(), 1)} for 22-28 days, "
      f"and is lowest ({pct(pg.late_rate.iloc[-1], 1)}) for 36+ days (shortest minus longest: {dd[0] * 100:.1f} points, interval {dd[1] * 100:.1f} to {dd[2] * 100:.1f}). "
      "The severe rate is lowest for the shortest promises.\n")
    A("**[Interpretation]** The hypothesis that short promises are missed more often is **not supported** by the observed rates. Promised lead time is likely a proxy for other things "
      "(the distance a parcel must travel, region, product type), which this workstream did not examine **[Hypothesis]**. The lowest late rate in the 36+ day group may reflect a larger buffer (median early margin grows from 7 days in the shortest group to 25 days in the longest) **[Hypothesis]**, "
      "but the 22-28 day group has a bigger margin (14 days) than the shortest group and a higher late rate, so buffer size alone is not a sufficient explanation.\n")

    # ------------------------------------------------------------------ 9
    A("## 9. Sensitivity checks\n")
    A("![Sensitivity](figures/delivery_07_sensitivity.png)\n")
    st_ = pd.DataFrame({
        "Variant": sens.variant, "Delivered": sens.n_delivered.map(n), "Late rate [95% Wilson]": [f"{pct(r)} {ci(a, b)}" for r, a, b in zip(sens.late_rate, sens.late_lo, sens.late_hi)],
        "Change vs base (pp)": sens.late_rate_change_pp.map(lambda v: f"{v:+.2f}"), "Severe rate": sens.severe_rate.map(pct),
        "Median / p95 lead (d)": [f"{a:.2f} / {b:.2f}" for a, b in zip(sens.lead_median, sens.lead_p95)],
    })
    A(md(st_, list(st_.columns)) + "\n")
    A(f"**[Observed]** No variant moves the pooled late rate by more than {sens.late_rate_change_pp.abs().max():.2f} percentage points; every interval overlaps the base interval. "
      "The 0-day and 30-day maturity thresholds select the same cohorts as the base (the last cohort, 2018-08, ended 47 days before the extract end); the 60-day threshold drops 2018-08 and equals the 'window ends 2018-07' variant. "
      f"Excluding the {n(STATS['n_anomaly_orders_in_base'])} delivered orders with flagged timestamp-sequence anomalies changes the rate by {sens.late_rate_change_pp.iloc[-1]:+.2f} points; these anomalies concern the carrier leg, not the purchase and delivery timestamps used here.\n")
    A("**[Interpretation]** The pooled headline is robust to these choices. The sensitivity thresholds are assumptions, not proof that recent cohorts are completely observed. "
      "Sensitivity checks were run on the pooled rate; the 2018-07/08 monthly values remain the least certain.\n")

    # ------------------------------------------------------------------ 10
    A("## 10. Key findings\n")
    A(f"1. **[Observed]** {pct(o['late_rate'], 1)} of delivered orders are late by calendar date ({n(o['n_late'])} of {n(o['n_delivered'])}; 95% interval {ci(*o['late_ci'])}); {pct(o['severe_rate'], 1)} are more than 7 days late.\n"
      f"2. **[Observed]** Lateness is concentrated in time: {', '.join(d['top3_months'])} account for {pct(d['top3_late_share'], 0)} of late orders from {pct(d['top3_delivered_share'], 0)} of delivered orders; the other 17 cohorts average {pct(d['rest_rate'], 1)}.\n"
      f"3. **[Observed]** The typical order is early: median {abs(ps['error_p50']):.0f} days before the promised date; median lead time {lo_['median']:.1f} days against a median promise of {ps['promised_lead_median']:.0f}.\n"
      f"4. **[Observed]** {pct((ft['cancelled_unavailable'] + ft['open_past_promise']) / ft['n_orders'], 1)} of orders never reached delivered status ({pct(ft['cancelled_unavailable'] / ft['n_orders'], 1)} cancelled/unavailable, {pct(ft['open_past_promise'] / ft['n_orders'], 1)} open past promise). These are not counted as delivery failures.\n"
      f"5. **[Observed]** High-volume months have a higher pooled late rate, but volume is confounded with time and the relationship is inconsistent across months; promised-lead mix does not explain the variation; shorter promises are not associated with more lateness.\n"
      "6. **[Observed]** The headline late rate is stable (within about 0.1 pp) across the window, maturity and anomaly sensitivities.\n")

    A("**Status of the blueprint hypotheses for this workstream**\n")
    A(md(pd.DataFrame([
        ["H1.1 Late rate is higher in peak-demand months", "Partly supported (association)", f"2017-11: {pct(pk['peak_rate'], 1)} vs {pct(pk['neighbour_rate'], 1)} in adjacent months; but the highest cohorts (2018-02, 2018-03) are not the highest-volume months, and volume is confounded with time"],
        ["H1.2 Short promises are missed more often", "Not supported", f"Late rate {pct(pg.late_rate.iloc[0], 1)} (<=14 d) vs {pct(pg.late_rate.max(), 1)} (22-28 d) vs {pct(pg.late_rate.iloc[-1], 1)} (36+ d); not monotone"],
        ["H1.3 Recent cohorts not comparable with mature ones", "Not resolved", "Pooled rate insensitive to maturity thresholds; the 2018-07/08 monthly p95 and severe rates may be affected by incomplete observation"],
        ["H1.4 Purchase weekday relates to lateness", "Not analysed", "Low-priority exploratory hypothesis"],
    ]), ["Hypothesis", "Status", "Basis"]) + "\n")

    # ------------------------------------------------------------------ 11
    A("## 11. Uncertainty\n")
    A("- Wilson and Newcombe intervals assume independent orders. Orders cluster within customers, sellers, regions and calendar days, so true uncertainty is larger, especially for month-level comparisons.\n"
      "- Bootstrap intervals (1,000 resamples overall, 500 per month, seed 20240901) resample orders independently.\n"
      "- Month-level patterns rest on 20 cohorts; correlations across months are descriptive, not inferential.\n"
      "- Delivered-only rates are conditional on observed delivery; the open-order scenario (Section 7) shows sensitivity, not an estimate.\n")

    # ------------------------------------------------------------------ 12
    A("## 12. Business implications (what these data support)\n")
    A("1. **Treat delivery reliability as an episode-management problem.** Roughly half of late orders sit in three cohorts. Monitoring monthly late and severe-late rates with control limits, "
      "and reviewing capacity and carrier performance ahead of known peaks (e.g. November), is more targeted than a uniform improvement programme. Whether those episodes had operational causes needs operations data not present here.\n"
      "2. **The promise appears generous for typical orders but did not adapt to slow periods.** Median early margin is 12 days, yet during the worst cohorts the promised lead times looked like other months. "
      "A promise that widens when lead-time p90/p95 rise would be one option to evaluate; shortening promises generally would raise the late rate unless the slow tail is controlled. This is a hypothesis to test, not a finding.\n"
      "3. **Follow up the unresolved orders.** 1,699 open orders past their promised date and 1,182 cancelled/unavailable orders are 2.9% of orders. Operations should establish the true status of the open ones before they are counted as failures, and understand the reasons for cancellation/unavailability.\n"
      "4. **Watch the 2018-08 cohort.** Late rate rose to 6.2% while promised lead times shortened (median 14 days vs 20 in July). Whether tighter promises, incomplete observation or real slippage explain it cannot be determined here.\n"
      "5. **Next step (not done here):** examine whether the episodes concentrate in particular regions or sellers (Workstream 2).\n")

    # ------------------------------------------------------------------ 13
    A("## 13. Limitations\n")
    A("- Conditional on delivery: cancelled, unavailable and open orders are outside delivery KPIs (Section 7).\n"
      "- Observational only: no causal conclusion about volume, promises, carriers or sellers is drawn.\n"
      "- Right-censoring in the latest cohorts; the 30/60-day maturity thresholds are sensitivity assumptions.\n"
      "- Time zones of timestamps are undocumented; calendar-date lateness assumes comparable dates.\n"
      "- 1,369 delivered window orders have timestamp-sequence anomalies (retained in primary KPIs; excluded in the sensitivity).\n"
      "- Promised-lead groups and the high-volume rule were fixed before examining outcomes, but their edges are judgement-based.\n"
      "- Single marketplace, 2017-2018 data; findings describe this dataset, not current operations.\n"
      "- Weekday of purchase (blueprint hypothesis H1.4, low priority) was not analysed.\n")

    # ------------------------------------------------------------------ 14
    A("## 14. Validation and tests\n")
    A(f"- Full test run (`python -m pytest`): **{pytest_summary}** (exit code {rc}); {sum(1 for _, s in cases if s == 'PASS')} of {len(cases)} cases passed.\n"
      "- Every primary SQL result (monthly counts, quantiles, promise-error distribution, severity bands, fulfilment classes, promised-lead groups, standardisation, high-volume rule, all six sensitivity variants) "
      "is recomputed independently in pandas from the raw CSVs and compared in `tests/test_delivery_reliability.py`; Wilson intervals are compared with SciPy, Newcombe with a published example.\n"
      "- **Model defect found and fixed during this workstream:** `ts_sequence_violation` and `carrier_leg_unreliable` were NULL (not FALSE) for orders with missing timestamps, so "
      "`WHERE NOT ts_sequence_violation` silently dropped 15 delivered orders and every non-delivered order. The established TRUE counts (1,382) and all populations were unaffected; "
      "the flags are now coalesced to FALSE, a regression test and a build assertion were added, and the model was rebuilt (34 build assertions, all established anchors unchanged).\n")
    A(md(pd.DataFrame(cases, columns=["Test", "Result"]), ["Test", "Result"]) + "\n")

    # ------------------------------------------------------------------ 15
    A("## 15. Reproduction\n")
    A("```\npython scripts/build_model.py\npython analysis/delivery_reliability.py      # tables, figures, stats JSON\n"
      "python analysis/build_delivery_report.py      # this report\n```\n"
      "SQL: `sql/analysis/delivery/*.sql`; tables: `reports/tables/delivery_*.csv`; figures: `reports/figures/delivery_*.png`; stats: `reports/delivery_reliability_stats.json`.\n")
    OUT.write_text("\n".join(w) + "\n", encoding="utf-8")
    print(f"wrote {OUT} (pytest exit code {rc})")
    return rc


if __name__ == "__main__":
    sys.exit(main())
